<a href="https://colab.research.google.com/github/svitlana2299/Hw_ds/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [7]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
a = list(range(1, 11))
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [19]:
m_1 = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]], dtype=int)

print(m_1)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [3]:
m_1 = np.zeros((3, 3), dtype=int)
print(m_1)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [12]:
matrix_1 = np.random.randint(1, 11, (5, 5))
print(matrix_1)

[[ 5  2 10  9  8]
 [ 5  7  8  7  2]
 [ 2  9  6  2  1]
 [ 1  1  8  3  1]
 [ 7  4  1  4  8]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [14]:
matrix_2 = np.random.rand(4, 4)
print(matrix_2)

[[0.0639952  0.2683113  0.43256616 0.13650928]
 [0.64191061 0.36817797 0.63557398 0.97124163]
 [0.92723262 0.33718978 0.03299554 0.46864491]
 [0.55302335 0.88202927 0.93724674 0.61626707]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [16]:
matrix_3 = np.random.randint(1, 11, (5, 5))
matrix_4 = np.random.randint(1, 11, (5, 5))
print(matrix_3)
print(matrix_4)
print(matrix_3 + matrix_4)
print(matrix_3 - matrix_4)
print(matrix_3 * matrix_4)

[[ 2 10  7  6  8]
 [ 7  2  5  7  8]
 [10  7  6  8  9]
 [ 7  1  7  1  8]
 [ 9 10  9  4  7]]
[[9 4 4 2 5]
 [8 7 6 9 4]
 [1 2 2 9 8]
 [3 6 9 5 1]
 [4 6 3 1 6]]
[[11 14 11  8 13]
 [15  9 11 16 12]
 [11  9  8 17 17]
 [10  7 16  6  9]
 [13 16 12  5 13]]
[[-7  6  3  4  3]
 [-1 -5 -1 -2  4]
 [ 9  5  4 -1  1]
 [ 4 -5 -2 -4  7]
 [ 5  4  6  3  1]]
[[18 40 28 12 40]
 [56 14 30 63 32]
 [10 14 12 72 72]
 [21  6 63  5  8]
 [36 60 27  4 42]]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [18]:
v_1 = np.random.random(7)
v_2 = np.random.random(7)
print(v_1, v_2)
print(np.dot(v_1, v_2))

[0.43464015 0.05887596 0.77742086 0.49663844 0.2541014  0.16225096
 0.90071174] [0.41915316 0.72879906 0.15432513 0.93999489 0.6001001  0.94765923
 0.3842945 ]
1.4642861616200133


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [25]:
matrix_5 = np.random.randint(1, 11, (2, 2))
matrix_6 = np.random.randint(1, 11, (2, 3))
r = np.dot(matrix_5, matrix_6)
print(matrix_5)
print(matrix_6)
print(r)

[[ 5 10]
 [ 6  2]]
[[ 4 10  9]
 [ 3  1  4]]
[[50 60 85]
 [30 62 62]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [24]:
matrix_7 = np.random.randint(1, 11, (3, 3))
matrix_7_inv = np.linalg.inv(matrix_7)
print(matrix_7)
print(matrix_7_inv)

[[ 4  3  4]
 [10  1  6]
 [ 1  9 10]]
[[ 0.43137255 -0.05882353 -0.1372549 ]
 [ 0.92156863 -0.35294118 -0.15686275]
 [-0.87254902  0.32352941  0.25490196]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [26]:
matrix_8 = np.random.rand(4, 4)
matrix_8_t = matrix_8.T
print(matrix_8)
print(matrix_8_t)

[[0.42891804 0.49494748 0.67023443 0.13993027]
 [0.2010989  0.01276457 0.80083977 0.02352278]
 [0.54047043 0.04934134 0.97402524 0.74930712]
 [0.47796469 0.32491246 0.02180259 0.83974304]]
[[0.42891804 0.2010989  0.54047043 0.47796469]
 [0.49494748 0.01276457 0.04934134 0.32491246]
 [0.67023443 0.80083977 0.97402524 0.02180259]
 [0.13993027 0.02352278 0.74930712 0.83974304]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [31]:
matrix_9 = np.random.randint(1, 11, (3, 4))
v_3 = np.random.randint(1, 11, 4)
r = np.dot(matrix_9, v_3)
print(matrix_9)
print(v_3)
print(r)

[[10  5  8  8]
 [ 3  1  3  5]
 [ 3  7  4  2]]
[6 8 1 6]
[156  59  90]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [43]:
matrix_10 = np.random.rand(3, 4)
v_4 = np.random.rand(4)
r = np.dot(matrix_10, v_4)
print(matrix_10)
print(v_4)
print(r)

[[0.63770583 0.24197035 0.34111115 0.74580347]
 [0.57910134 0.91859191 0.24933972 0.50707309]
 [0.98186504 0.44345216 0.86305982 0.25357709]]
[0.59121552 0.79718958 0.774826   0.50471462]
[1.21063752 1.5237877  1.73071455]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [33]:
matrix_11 = np.random.randint(1, 11, (2, 2))
matrix_12 = np.random.randint(1, 11, (2, 2))
r = matrix_11 * matrix_12
print(matrix_11)
print(matrix_12)
print(r)

[[10  8]
 [ 1  7]]
[[3 2]
 [8 6]]
[[30 16]
 [ 8 42]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [34]:
matrix_13 = np.random.randint(1, 11, (2, 2))
matrix_14 = np.random.randint(1, 11, (2, 2))
r = np.dot(matrix_13, matrix_14)
print(matrix_13)
print(matrix_14)
print(r)

[[ 7  9]
 [ 7 10]]
[[ 6  6]
 [10  7]]
[[132 105]
 [142 112]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [37]:
matrix_15 = np.random.randint(1, 100, (5, 5))
print (matrix_15)
print(matrix_15.sum())

[[72 37 91 87 71]
 [28 92 44 73 60]
 [33 54 78 84 84]
 [73 50 22 43 89]
 [90 94 58 82 63]]
1652


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [38]:
matrix_16 = np.random.randint(1, 11, (4, 4))
matrix_17 = np.random.randint(1, 11, (4, 4))
r = matrix_16 - matrix_17
print(matrix_16)
print(matrix_17)
print(r)

[[ 7  1  1  4]
 [10  1  6  1]
 [ 4  5  2  5]
 [10  7  6  6]]
[[ 8  2 10  6]
 [ 9  1  7  9]
 [ 8  1  3  4]
 [ 8 10  4  3]]
[[-1 -1 -9 -2]
 [ 1  0 -1 -8]
 [-4  4 -1  1]
 [ 2 -3  2  3]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [39]:
matrix_18 = np.random.rand(3, 3)

row_sums = np.sum(matrix_18, axis=1)
column_vector = row_sums.reshape(-1, 1)

print(matrix_18)
print(column_vector)

[[0.23319329 0.06615377 0.96576411]
 [0.54854458 0.83731307 0.99198575]
 [0.69034712 0.23289328 0.13872371]]
[[1.26511117]
 [2.37784341]
 [1.06196411]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [41]:
matrix_19 = np.random.randint(1, 11, (3, 4))
squared_matrix_19 = np.square(matrix_19)
print(matrix_19)
print(squared_matrix_19)

[[ 9 10  5 10]
 [ 9  3  2 10]
 [ 9  2  3  2]]
[[ 81 100  25 100]
 [ 81   9   4 100]
 [ 81   4   9   4]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [42]:
v_5 = np.random.randint(1, 50, 4)
r = np.sqrt(v_5)
print(v_5)
print(r)

[31 40 31 17]
[5.56776436 6.32455532 5.56776436 4.12310563]
